// Code generated by protoc-gen-gogo.
// source: github.com/jsgilmore/gostorm/messages/messages.proto
// DO NOT EDIT!

package messages

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// discarding unused import gogoproto "code.google.com/p/gogoprotobuf/gogoproto/gogo.pb"
// discarding unused import nextproto "next/gogoprotobuf/nextproto/next.pb"

import ()

import ()

import ()

import io "io"
import code_google_com_p_gogoprotobuf_proto "code.google.com/p/gogoprotobuf/proto"

import fmt "fmt"
import strings "strings"
import reflect "reflect"

import fmt1 "fmt"
import bytes "bytes"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type TaskComponentMapping struct {
	Task             string `protobuf:"bytes,1,opt" json:"Task"`
	Component        string `protobuf:"bytes,2,opt" json:"Component"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TaskComponentMapping) Reset()      { *m = TaskComponentMapping{} }
func (*TaskComponentMapping) ProtoMessage() {}

type Topology struct {
	TaskId                int64                   `protobuf:"varint,1,opt" json:"TaskId"`
	TaskComponentMappings []*TaskComponentMapping `protobuf:"bytes,2,rep" json:"TaskComponentMappings,omitempty"`
	XXX_unrecognized      []byte                  `json:"-"`
}

func (m *Topology) Reset()      { *m = Topology{} }
func (*Topology) ProtoMessage() {}

func (m *Topology) GetTaskComponentMappings() []*TaskComponentMapping {
	if m != nil {
		return m.TaskComponentMappings
	}
	return nil
}

type Conf struct {
	Key              string `protobuf:"bytes,1,opt" json:"Key"`
	Value            string `protobuf:"bytes,2,opt" json:"Value"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Conf) Reset()      { *m = Conf{} }
func (*Conf) ProtoMessage() {}

type Context struct {
	PidDir           string    `protobuf:"bytes,1,opt" json:"PidDir"`
	Topology         *Topology `protobuf:"bytes,2,opt" json:"Topology,omitempty"`
	Confs            []*Conf   `protobuf:"bytes,3,rep" json:"Confs,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Context) Reset()      { *m = Context{} }
func (*Context) ProtoMessage() {}

func (m *Context) GetTopology() *Topology {
	if m != nil {
		return m.Topology
	}
	return nil
}

func (m *Context) GetConfs() []*Conf {
	if m != nil {
		return m.Confs
	}
	return nil
}

type Pid struct {
	Pid              int32  `protobuf:"varint,1,opt" json:"Pid"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Pid) Reset()      { *m = Pid{} }
func (*Pid) ProtoMessage() {}

type TupleMetadata struct {
	Id               string `protobuf:"bytes,1,opt" json:"Id"`
	Comp             string `protobuf:"bytes,2,opt" json:"Comp"`
	Stream           string `protobuf:"bytes,3,opt" json:"Stream"`
	Task             int64  `protobuf:"varint,4,opt" json:"Task"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TupleMetadata) Reset()      { *m = TupleMetadata{} }
func (*TupleMetadata) ProtoMessage() {}

type TupleProto struct {
	TupleMetadata    *TupleMetadata `protobuf:"bytes,1,opt" json:"TupleMetadata,omitempty"`
	Contents         [][]byte       `protobuf:"bytes,2,rep" json:"Contents,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *TupleProto) Reset()      { *m = TupleProto{} }
func (*TupleProto) ProtoMessage() {}

func (m *TupleProto) GetTupleMetadata() *TupleMetadata {
	if m != nil {
		return m.TupleMetadata
	}
	return nil
}

func (m *TupleProto) GetContents() [][]byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type TaskIds struct {
	TaskIds          []int32 `protobuf:"varint,1,rep" json:"TaskIds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TaskIds) Reset()      { *m = TaskIds{} }
func (*TaskIds) ProtoMessage() {}

func (m *TaskIds) GetTaskIds() []int32 {
	if m != nil {
		return m.TaskIds
	}
	return nil
}

type SpoutMsg struct {
	Command          string `protobuf:"bytes,1,opt" json:"Command"`
	Id               string `protobuf:"bytes,2,opt" json:"Id"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SpoutMsg) Reset()      { *m = SpoutMsg{} }
func (*SpoutMsg) ProtoMessage() {}

type EmissionMetadata struct {
	Command          string   `protobuf:"bytes,1,opt" json:"Command"`
	Id               *string  `protobuf:"bytes,2,opt" json:"Id,omitempty"`
	Anchors          []string `protobuf:"bytes,3,rep" json:"Anchors,omitempty"`
	Stream           *string  `protobuf:"bytes,4,opt" json:"Stream,omitempty"`
	Task             *int64   `protobuf:"varint,5,opt" json:"Task,omitempty"`
	Msg              *string  `protobuf:"bytes,6,opt" json:"Msg,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *EmissionMetadata) Reset()      { *m = EmissionMetadata{} }
func (*EmissionMetadata) ProtoMessage() {}

func (m *EmissionMetadata) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *EmissionMetadata) GetAnchors() []string {
	if m != nil {
		return m.Anchors
	}
	return nil
}

func (m *EmissionMetadata) GetStream() string {
	if m != nil && m.Stream != nil {
		return *m.Stream
	}
	return ""
}

func (m *EmissionMetadata) GetTask() int64 {
	if m != nil && m.Task != nil {
		return *m.Task
	}
	return 0
}

func (m *EmissionMetadata) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type EmissionProto struct {
	EmissionMetadata *EmissionMetadata `protobuf:"bytes,1,opt" json:"EmissionMetadata,omitempty"`
	Contents         [][]byte          `protobuf:"bytes,2,rep" json:"Contents,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *EmissionProto) Reset()      { *m = EmissionProto{} }
func (*EmissionProto) ProtoMessage() {}

func (m *EmissionProto) GetEmissionMetadata() *EmissionMetadata {
	if m != nil {
		return m.EmissionMetadata
	}
	return nil
}

func (m *EmissionProto) GetContents() [][]byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Test struct {
	Name             string `protobuf:"bytes,1,opt" json:"Name"`
	Number           int64  `protobuf:"varint,2,opt" json:"Number"`
	Data             []byte `protobuf:"bytes,3,opt" json:"Data"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Test) Reset()      { *m = Test{} }
func (*Test) ProtoMessage() {}

func init() {
}
func (m *TaskComponentMapping) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Task = string(data[index:postIndex])
			index = postIndex
		case 2:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Component = string(data[index:postIndex])
			index = postIndex
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *Topology) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return proto.ErrWrongType
			}
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				m.TaskId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskComponentMappings = append(m.TaskComponentMappings, &TaskComponentMapping{})
			m.TaskComponentMappings[len(m.TaskComponentMappings)-1].Unmarshal(data[index:postIndex])
			index = postIndex
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *Conf) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(data[index:postIndex])
			index = postIndex
		case 2:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(data[index:postIndex])
			index = postIndex
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *Context) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PidDir = string(data[index:postIndex])
			index = postIndex
		case 2:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Topology = &Topology{}
			if err := m.Topology.Unmarshal(data[index:postIndex]); err != nil {
				return err
			}
			index = postIndex
		case 3:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Confs = append(m.Confs, &Conf{})
			m.Confs[len(m.Confs)-1].Unmarshal(data[index:postIndex])
			index = postIndex
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *Pid) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return proto.ErrWrongType
			}
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				m.Pid |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *TupleMetadata) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(data[index:postIndex])
			index = postIndex
		case 2:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comp = string(data[index:postIndex])
			index = postIndex
		case 3:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stream = string(data[index:postIndex])
			index = postIndex
		case 4:
			if wireType != 0 {
				return proto.ErrWrongType
			}
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				m.Task |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *TupleProto) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TupleMetadata = &TupleMetadata{}
			if err := m.TupleMetadata.Unmarshal(data[index:postIndex]); err != nil {
				return err
			}
			index = postIndex
		case 2:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contents = append(m.Contents, make([]byte, postIndex-index))
			copy(m.Contents[len(m.Contents)-1], data[index:postIndex])
			index = postIndex
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *TaskIds) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return proto.ErrWrongType
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TaskIds = append(m.TaskIds, v)
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *SpoutMsg) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Command = string(data[index:postIndex])
			index = postIndex
		case 2:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(data[index:postIndex])
			index = postIndex
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *EmissionMetadata) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Command = string(data[index:postIndex])
			index = postIndex
		case 2:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(data[index:postIndex])
			m.Id = &s
			index = postIndex
		case 3:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Anchors = append(m.Anchors, string(data[index:postIndex]))
			index = postIndex
		case 4:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(data[index:postIndex])
			m.Stream = &s
			index = postIndex
		case 5:
			if wireType != 0 {
				return proto.ErrWrongType
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				v |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Task = &v
		case 6:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(data[index:postIndex])
			m.Msg = &s
			index = postIndex
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *EmissionProto) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EmissionMetadata = &EmissionMetadata{}
			if err := m.EmissionMetadata.Unmarshal(data[index:postIndex]); err != nil {
				return err
			}
			index = postIndex
		case 2:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contents = append(m.Contents, make([]byte, postIndex-index))
			copy(m.Contents[len(m.Contents)-1], data[index:postIndex])
			index = postIndex
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *Test) Unmarshal(data []byte) error {
	l := len(data)
	index := 0
	for index < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if index >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[index]
			index++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + int(stringLen)
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(data[index:postIndex])
			index = postIndex
		case 2:
			if wireType != 0 {
				return proto.ErrWrongType
			}
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				m.Number |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return proto.ErrWrongType
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if index >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[index]
				index++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := index + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, data[index:postIndex]...)
			index = postIndex
		default:
			var sizeOfWire int
			for {
				sizeOfWire++
				wire >>= 7
				if wire == 0 {
					break
				}
			}
			index -= sizeOfWire
			skippy, err := code_google_com_p_gogoprotobuf_proto.Skip(data[index:])
			if err != nil {
				return err
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[index:index+skippy]...)
			index += skippy
		}
	}
	return nil
}
func (m *TaskComponentMapping) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *TaskComponentMapping) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0xa
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Task)))
	i += copy(data[i:], m.Task)
	data[i] = 0x12
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Component)))
	i += copy(data[i:], m.Component)
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *Topology) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Topology) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0x8
	i++
	i = encodeVarintMessages(data, i, uint64(m.TaskId))
	if len(m.TaskComponentMappings) > 0 {
		for _, msg := range m.TaskComponentMappings {
			data[i] = 0x12
			i++
			i = encodeVarintMessages(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *Conf) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Conf) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0xa
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Key)))
	i += copy(data[i:], m.Key)
	data[i] = 0x12
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Value)))
	i += copy(data[i:], m.Value)
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *Context) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Context) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0xa
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.PidDir)))
	i += copy(data[i:], m.PidDir)
	if m.Topology != nil {
		data[i] = 0x12
		i++
		i = encodeVarintMessages(data, i, uint64(m.Topology.Size()))
		n1, err := m.Topology.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Confs) > 0 {
		for _, msg := range m.Confs {
			data[i] = 0x1a
			i++
			i = encodeVarintMessages(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *Pid) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Pid) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0x8
	i++
	i = encodeVarintMessages(data, i, uint64(m.Pid))
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *TupleMetadata) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *TupleMetadata) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0xa
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Id)))
	i += copy(data[i:], m.Id)
	data[i] = 0x12
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Comp)))
	i += copy(data[i:], m.Comp)
	data[i] = 0x1a
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Stream)))
	i += copy(data[i:], m.Stream)
	data[i] = 0x20
	i++
	i = encodeVarintMessages(data, i, uint64(m.Task))
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *TupleProto) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *TupleProto) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TupleMetadata != nil {
		data[i] = 0xa
		i++
		i = encodeVarintMessages(data, i, uint64(m.TupleMetadata.Size()))
		n2, err := m.TupleMetadata.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if len(m.Contents) > 0 {
		for _, b := range m.Contents {
			data[i] = 0x12
			i++
			i = encodeVarintMessages(data, i, uint64(len(b)))
			i += copy(data[i:], b)
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *TaskIds) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *TaskIds) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TaskIds) > 0 {
		for _, num := range m.TaskIds {
			data[i] = 0x8
			i++
			for num >= 1<<7 {
				data[i] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				i++
			}
			data[i] = uint8(num)
			i++
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *SpoutMsg) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *SpoutMsg) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0xa
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Command)))
	i += copy(data[i:], m.Command)
	data[i] = 0x12
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Id)))
	i += copy(data[i:], m.Id)
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *EmissionMetadata) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *EmissionMetadata) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0xa
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Command)))
	i += copy(data[i:], m.Command)
	if m.Id != nil {
		data[i] = 0x12
		i++
		i = encodeVarintMessages(data, i, uint64(len(*m.Id)))
		i += copy(data[i:], *m.Id)
	}
	if len(m.Anchors) > 0 {
		for _, s := range m.Anchors {
			data[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				data[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			data[i] = uint8(l)
			i++
			i += copy(data[i:], s)
		}
	}
	if m.Stream != nil {
		data[i] = 0x22
		i++
		i = encodeVarintMessages(data, i, uint64(len(*m.Stream)))
		i += copy(data[i:], *m.Stream)
	}
	if m.Task != nil {
		data[i] = 0x28
		i++
		i = encodeVarintMessages(data, i, uint64(*m.Task))
	}
	if m.Msg != nil {
		data[i] = 0x32
		i++
		i = encodeVarintMessages(data, i, uint64(len(*m.Msg)))
		i += copy(data[i:], *m.Msg)
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *EmissionProto) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *EmissionProto) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.EmissionMetadata != nil {
		data[i] = 0xa
		i++
		i = encodeVarintMessages(data, i, uint64(m.EmissionMetadata.Size()))
		n3, err := m.EmissionMetadata.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if len(m.Contents) > 0 {
		for _, b := range m.Contents {
			data[i] = 0x12
			i++
			i = encodeVarintMessages(data, i, uint64(len(b)))
			i += copy(data[i:], b)
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func (m *Test) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Test) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	data[i] = 0xa
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Name)))
	i += copy(data[i:], m.Name)
	data[i] = 0x10
	i++
	i = encodeVarintMessages(data, i, uint64(m.Number))
	data[i] = 0x1a
	i++
	i = encodeVarintMessages(data, i, uint64(len(m.Data)))
	i += copy(data[i:], m.Data)
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}
func encodeFixed64Messages(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Messages(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMessages(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (this *TaskComponentMapping) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TaskComponentMapping{`,
		`Task:` + fmt.Sprintf("%v", this.Task) + `,`,
		`Component:` + fmt.Sprintf("%v", this.Component) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Topology) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Topology{`,
		`TaskId:` + fmt.Sprintf("%v", this.TaskId) + `,`,
		`TaskComponentMappings:` + strings.Replace(fmt.Sprintf("%v", this.TaskComponentMappings), "TaskComponentMapping", "TaskComponentMapping", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Conf) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Conf{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Context) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Context{`,
		`PidDir:` + fmt.Sprintf("%v", this.PidDir) + `,`,
		`Topology:` + strings.Replace(fmt.Sprintf("%v", this.Topology), "Topology", "Topology", 1) + `,`,
		`Confs:` + strings.Replace(fmt.Sprintf("%v", this.Confs), "Conf", "Conf", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Pid) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Pid{`,
		`Pid:` + fmt.Sprintf("%v", this.Pid) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TupleMetadata) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TupleMetadata{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`Comp:` + fmt.Sprintf("%v", this.Comp) + `,`,
		`Stream:` + fmt.Sprintf("%v", this.Stream) + `,`,
		`Task:` + fmt.Sprintf("%v", this.Task) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TupleProto) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TupleProto{`,
		`TupleMetadata:` + strings.Replace(fmt.Sprintf("%v", this.TupleMetadata), "TupleMetadata", "TupleMetadata", 1) + `,`,
		`Contents:` + fmt.Sprintf("%v", this.Contents) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TaskIds) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TaskIds{`,
		`TaskIds:` + fmt.Sprintf("%v", this.TaskIds) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SpoutMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SpoutMsg{`,
		`Command:` + fmt.Sprintf("%v", this.Command) + `,`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EmissionMetadata) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EmissionMetadata{`,
		`Command:` + fmt.Sprintf("%v", this.Command) + `,`,
		`Id:` + valueToStringMessages(this.Id) + `,`,
		`Anchors:` + fmt.Sprintf("%v", this.Anchors) + `,`,
		`Stream:` + valueToStringMessages(this.Stream) + `,`,
		`Task:` + valueToStringMessages(this.Task) + `,`,
		`Msg:` + valueToStringMessages(this.Msg) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EmissionProto) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EmissionProto{`,
		`EmissionMetadata:` + strings.Replace(fmt.Sprintf("%v", this.EmissionMetadata), "EmissionMetadata", "EmissionMetadata", 1) + `,`,
		`Contents:` + fmt.Sprintf("%v", this.Contents) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Test) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Test{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Number:` + fmt.Sprintf("%v", this.Number) + `,`,
		`Data:` + fmt.Sprintf("%v", this.Data) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMessages(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TaskComponentMapping) Size() (n int) {
	var l int
	_ = l
	l = len([]byte(m.Task))
	n += 1 + l + sovMessages(uint64(l))
	l = len([]byte(m.Component))
	n += 1 + l + sovMessages(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *Topology) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMessages(uint64(m.TaskId))
	if len(m.TaskComponentMappings) > 0 {
		for _, e := range m.TaskComponentMappings {
			l = e.Size()
			n += 1 + l + sovMessages(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *Conf) Size() (n int) {
	var l int
	_ = l
	l = len([]byte(m.Key))
	n += 1 + l + sovMessages(uint64(l))
	l = len([]byte(m.Value))
	n += 1 + l + sovMessages(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *Context) Size() (n int) {
	var l int
	_ = l
	l = len([]byte(m.PidDir))
	n += 1 + l + sovMessages(uint64(l))
	if m.Topology != nil {
		l = m.Topology.Size()
		n += 1 + l + sovMessages(uint64(l))
	}
	if len(m.Confs) > 0 {
		for _, e := range m.Confs {
			l = e.Size()
			n += 1 + l + sovMessages(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *Pid) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMessages(uint64(m.Pid))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *TupleMetadata) Size() (n int) {
	var l int
	_ = l
	l = len([]byte(m.Id))
	n += 1 + l + sovMessages(uint64(l))
	l = len([]byte(m.Comp))
	n += 1 + l + sovMessages(uint64(l))
	l = len([]byte(m.Stream))
	n += 1 + l + sovMessages(uint64(l))
	n += 1 + sovMessages(uint64(m.Task))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *TupleProto) Size() (n int) {
	var l int
	_ = l
	if m.TupleMetadata != nil {
		l = m.TupleMetadata.Size()
		n += 1 + l + sovMessages(uint64(l))
	}
	if len(m.Contents) > 0 {
		for _, b := range m.Contents {
			l = len(b)
			n += 1 + l + sovMessages(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *TaskIds) Size() (n int) {
	var l int
	_ = l
	if len(m.TaskIds) > 0 {
		for _, e := range m.TaskIds {
			n += 1 + sovMessages(uint64(e))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *SpoutMsg) Size() (n int) {
	var l int
	_ = l
	l = len([]byte(m.Command))
	n += 1 + l + sovMessages(uint64(l))
	l = len([]byte(m.Id))
	n += 1 + l + sovMessages(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *EmissionMetadata) Size() (n int) {
	var l int
	_ = l
	l = len([]byte(m.Command))
	n += 1 + l + sovMessages(uint64(l))
	if m.Id != nil {
		l = len([]byte(*m.Id))
		n += 1 + l + sovMessages(uint64(l))
	}
	if len(m.Anchors) > 0 {
		for _, s := range m.Anchors {
			l = len([]byte(s))
			n += 1 + l + sovMessages(uint64(l))
		}
	}
	if m.Stream != nil {
		l = len([]byte(*m.Stream))
		n += 1 + l + sovMessages(uint64(l))
	}
	if m.Task != nil {
		n += 1 + sovMessages(uint64(*m.Task))
	}
	if m.Msg != nil {
		l = len([]byte(*m.Msg))
		n += 1 + l + sovMessages(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *EmissionProto) Size() (n int) {
	var l int
	_ = l
	if m.EmissionMetadata != nil {
		l = m.EmissionMetadata.Size()
		n += 1 + l + sovMessages(uint64(l))
	}
	if len(m.Contents) > 0 {
		for _, b := range m.Contents {
			l = len(b)
			n += 1 + l + sovMessages(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}
func (m *Test) Size() (n int) {
	var l int
	_ = l
	l = len([]byte(m.Name))
	n += 1 + l + sovMessages(uint64(l))
	n += 1 + sovMessages(uint64(m.Number))
	l = len(m.Data)
	n += 1 + l + sovMessages(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMessages(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMessages(x uint64) (n int) {
	return sovMessages(uint64((x << 1) ^ uint64((int64(x) >> 63))))
	return sovMessages(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func NewPopulatedTaskComponentMapping(r randyMessages, easy bool) *TaskComponentMapping {
	this := &TaskComponentMapping{}
	this.Task = randStringMessages(r)
	this.Component = randStringMessages(r)
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 3)
	}
	return this
}

func NewPopulatedTopology(r randyMessages, easy bool) *Topology {
	this := &Topology{}
	this.TaskId = r.Int63()
	if r.Intn(10) != 0 {
		v1 := r.Intn(10)
		this.TaskComponentMappings = make([]*TaskComponentMapping, v1)
		for i := 0; i < v1; i++ {
			this.TaskComponentMappings[i] = NewPopulatedTaskComponentMapping(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 3)
	}
	return this
}

func NewPopulatedConf(r randyMessages, easy bool) *Conf {
	this := &Conf{}
	this.Key = randStringMessages(r)
	this.Value = randStringMessages(r)
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 3)
	}
	return this
}

func NewPopulatedContext(r randyMessages, easy bool) *Context {
	this := &Context{}
	this.PidDir = randStringMessages(r)
	if r.Intn(10) != 0 {
		this.Topology = NewPopulatedTopology(r, easy)
	}
	if r.Intn(10) != 0 {
		v2 := r.Intn(10)
		this.Confs = make([]*Conf, v2)
		for i := 0; i < v2; i++ {
			this.Confs[i] = NewPopulatedConf(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 4)
	}
	return this
}

func NewPopulatedPid(r randyMessages, easy bool) *Pid {
	this := &Pid{}
	this.Pid = r.Int31()
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 2)
	}
	return this
}

func NewPopulatedTupleMetadata(r randyMessages, easy bool) *TupleMetadata {
	this := &TupleMetadata{}
	this.Id = randStringMessages(r)
	this.Comp = randStringMessages(r)
	this.Stream = randStringMessages(r)
	this.Task = r.Int63()
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 5)
	}
	return this
}

func NewPopulatedTupleProto(r randyMessages, easy bool) *TupleProto {
	this := &TupleProto{}
	if r.Intn(10) != 0 {
		this.TupleMetadata = NewPopulatedTupleMetadata(r, easy)
	}
	if r.Intn(10) != 0 {
		v3 := r.Intn(100)
		this.Contents = make([][]byte, v3)
		for i := 0; i < v3; i++ {
			v4 := r.Intn(100)
			this.Contents[i] = make([]byte, v4)
			for j := 0; j < v4; j++ {
				this.Contents[i][j] = byte(r.Intn(256))
			}
		}
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 3)
	}
	return this
}

func NewPopulatedTaskIds(r randyMessages, easy bool) *TaskIds {
	this := &TaskIds{}
	if r.Intn(10) != 0 {
		v5 := r.Intn(100)
		this.TaskIds = make([]int32, v5)
		for i := 0; i < v5; i++ {
			this.TaskIds[i] = r.Int31()
		}
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 2)
	}
	return this
}

func NewPopulatedSpoutMsg(r randyMessages, easy bool) *SpoutMsg {
	this := &SpoutMsg{}
	this.Command = randStringMessages(r)
	this.Id = randStringMessages(r)
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 3)
	}
	return this
}

func NewPopulatedEmissionMetadata(r randyMessages, easy bool) *EmissionMetadata {
	this := &EmissionMetadata{}
	this.Command = randStringMessages(r)
	if r.Intn(10) != 0 {
		v6 := randStringMessages(r)
		this.Id = &v6
	}
	if r.Intn(10) != 0 {
		v7 := r.Intn(10)
		this.Anchors = make([]string, v7)
		for i := 0; i < v7; i++ {
			this.Anchors[i] = randStringMessages(r)
		}
	}
	if r.Intn(10) != 0 {
		v8 := randStringMessages(r)
		this.Stream = &v8
	}
	if r.Intn(10) != 0 {
		v9 := r.Int63()
		this.Task = &v9
	}
	if r.Intn(10) != 0 {
		v10 := randStringMessages(r)
		this.Msg = &v10
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 7)
	}
	return this
}

func NewPopulatedEmissionProto(r randyMessages, easy bool) *EmissionProto {
	this := &EmissionProto{}
	if r.Intn(10) != 0 {
		this.EmissionMetadata = NewPopulatedEmissionMetadata(r, easy)
	}
	if r.Intn(10) != 0 {
		v11 := r.Intn(100)
		this.Contents = make([][]byte, v11)
		for i := 0; i < v11; i++ {
			v12 := r.Intn(100)
			this.Contents[i] = make([]byte, v12)
			for j := 0; j < v12; j++ {
				this.Contents[i][j] = byte(r.Intn(256))
			}
		}
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 3)
	}
	return this
}

func NewPopulatedTest(r randyMessages, easy bool) *Test {
	this := &Test{}
	this.Name = randStringMessages(r)
	this.Number = r.Int63()
	v13 := r.Intn(100)
	this.Data = make([]byte, v13)
	for i := 0; i < v13; i++ {
		this.Data[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessages(r, 4)
	}
	return this
}

type randyMessages interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneMessages(r randyMessages) rune {
	res := rune(r.Uint32() % 1112064)
	if 55296 <= res {
		res += 2047
	}
	return res
}
func randStringMessages(r randyMessages) string {
	v14 := r.Intn(100)
	tmps := make([]rune, v14)
	for i := 0; i < v14; i++ {
		tmps[i] = randUTF8RuneMessages(r)
	}
	return string(tmps)
}
func randUnrecognizedMessages(r randyMessages, maxFieldNumber int) (data []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		data = randFieldMessages(data, r, fieldNumber, wire)
	}
	return data
}
func randFieldMessages(data []byte, r randyMessages, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		data = encodeVarintPopulateMessages(data, uint64(key))
		data = encodeVarintPopulateMessages(data, uint64(r.Int63()))
	case 1:
		data = encodeVarintPopulateMessages(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		data = encodeVarintPopulateMessages(data, uint64(key))
		ll := r.Intn(100)
		data = encodeVarintPopulateMessages(data, uint64(ll))
		for j := 0; j < ll; j++ {
			data = append(data, byte(r.Intn(256)))
		}
	default:
		data = encodeVarintPopulateMessages(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return data
}
func encodeVarintPopulateMessages(data []byte, v uint64) []byte {
	for v >= 1<<7 {
		data = append(data, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	data = append(data, uint8(v))
	return data
}
func (this *TaskComponentMapping) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*TaskComponentMapping)
	if !ok {
		return fmt1.Errorf("that is not of type *TaskComponentMapping")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *TaskComponentMapping but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *TaskComponentMappingbut is not nil && this == nil")
	}
	if this.Task != that1.Task {
		return fmt1.Errorf("Task this(%v) Not Equal that(%v)", this.Task, that1.Task)
	}
	if this.Component != that1.Component {
		return fmt1.Errorf("Component this(%v) Not Equal that(%v)", this.Component, that1.Component)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *TaskComponentMapping) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*TaskComponentMapping)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Task != that1.Task {
		return false
	}
	if this.Component != that1.Component {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Topology) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Topology)
	if !ok {
		return fmt1.Errorf("that is not of type *Topology")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *Topology but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *Topologybut is not nil && this == nil")
	}
	if this.TaskId != that1.TaskId {
		return fmt1.Errorf("TaskId this(%v) Not Equal that(%v)", this.TaskId, that1.TaskId)
	}
	if len(this.TaskComponentMappings) != len(that1.TaskComponentMappings) {
		return fmt1.Errorf("TaskComponentMappings this(%v) Not Equal that(%v)", len(this.TaskComponentMappings), len(that1.TaskComponentMappings))
	}
	for i := range this.TaskComponentMappings {
		if !this.TaskComponentMappings[i].Equal(that1.TaskComponentMappings[i]) {
			return fmt1.Errorf("TaskComponentMappings this[%v](%v) Not Equal that[%v](%v)", i, this.TaskComponentMappings[i], i, that1.TaskComponentMappings[i])
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *Topology) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Topology)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.TaskId != that1.TaskId {
		return false
	}
	if len(this.TaskComponentMappings) != len(that1.TaskComponentMappings) {
		return false
	}
	for i := range this.TaskComponentMappings {
		if !this.TaskComponentMappings[i].Equal(that1.TaskComponentMappings[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Conf) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Conf)
	if !ok {
		return fmt1.Errorf("that is not of type *Conf")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *Conf but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *Confbut is not nil && this == nil")
	}
	if this.Key != that1.Key {
		return fmt1.Errorf("Key this(%v) Not Equal that(%v)", this.Key, that1.Key)
	}
	if this.Value != that1.Value {
		return fmt1.Errorf("Value this(%v) Not Equal that(%v)", this.Value, that1.Value)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *Conf) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Conf)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Key != that1.Key {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Context) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Context)
	if !ok {
		return fmt1.Errorf("that is not of type *Context")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *Context but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *Contextbut is not nil && this == nil")
	}
	if this.PidDir != that1.PidDir {
		return fmt1.Errorf("PidDir this(%v) Not Equal that(%v)", this.PidDir, that1.PidDir)
	}
	if !this.Topology.Equal(that1.Topology) {
		return fmt1.Errorf("Topology this(%v) Not Equal that(%v)", this.Topology, that1.Topology)
	}
	if len(this.Confs) != len(that1.Confs) {
		return fmt1.Errorf("Confs this(%v) Not Equal that(%v)", len(this.Confs), len(that1.Confs))
	}
	for i := range this.Confs {
		if !this.Confs[i].Equal(that1.Confs[i]) {
			return fmt1.Errorf("Confs this[%v](%v) Not Equal that[%v](%v)", i, this.Confs[i], i, that1.Confs[i])
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *Context) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Context)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.PidDir != that1.PidDir {
		return false
	}
	if !this.Topology.Equal(that1.Topology) {
		return false
	}
	if len(this.Confs) != len(that1.Confs) {
		return false
	}
	for i := range this.Confs {
		if !this.Confs[i].Equal(that1.Confs[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Pid) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Pid)
	if !ok {
		return fmt1.Errorf("that is not of type *Pid")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *Pid but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *Pidbut is not nil && this == nil")
	}
	if this.Pid != that1.Pid {
		return fmt1.Errorf("Pid this(%v) Not Equal that(%v)", this.Pid, that1.Pid)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *Pid) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Pid)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Pid != that1.Pid {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *TupleMetadata) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*TupleMetadata)
	if !ok {
		return fmt1.Errorf("that is not of type *TupleMetadata")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *TupleMetadata but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *TupleMetadatabut is not nil && this == nil")
	}
	if this.Id != that1.Id {
		return fmt1.Errorf("Id this(%v) Not Equal that(%v)", this.Id, that1.Id)
	}
	if this.Comp != that1.Comp {
		return fmt1.Errorf("Comp this(%v) Not Equal that(%v)", this.Comp, that1.Comp)
	}
	if this.Stream != that1.Stream {
		return fmt1.Errorf("Stream this(%v) Not Equal that(%v)", this.Stream, that1.Stream)
	}
	if this.Task != that1.Task {
		return fmt1.Errorf("Task this(%v) Not Equal that(%v)", this.Task, that1.Task)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *TupleMetadata) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*TupleMetadata)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Comp != that1.Comp {
		return false
	}
	if this.Stream != that1.Stream {
		return false
	}
	if this.Task != that1.Task {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *TupleProto) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*TupleProto)
	if !ok {
		return fmt1.Errorf("that is not of type *TupleProto")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *TupleProto but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *TupleProtobut is not nil && this == nil")
	}
	if !this.TupleMetadata.Equal(that1.TupleMetadata) {
		return fmt1.Errorf("TupleMetadata this(%v) Not Equal that(%v)", this.TupleMetadata, that1.TupleMetadata)
	}
	if len(this.Contents) != len(that1.Contents) {
		return fmt1.Errorf("Contents this(%v) Not Equal that(%v)", len(this.Contents), len(that1.Contents))
	}
	for i := range this.Contents {
		if !bytes.Equal(this.Contents[i], that1.Contents[i]) {
			return fmt1.Errorf("Contents this[%v](%v) Not Equal that[%v](%v)", i, this.Contents[i], i, that1.Contents[i])
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *TupleProto) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*TupleProto)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.TupleMetadata.Equal(that1.TupleMetadata) {
		return false
	}
	if len(this.Contents) != len(that1.Contents) {
		return false
	}
	for i := range this.Contents {
		if !bytes.Equal(this.Contents[i], that1.Contents[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *TaskIds) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*TaskIds)
	if !ok {
		return fmt1.Errorf("that is not of type *TaskIds")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *TaskIds but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *TaskIdsbut is not nil && this == nil")
	}
	if len(this.TaskIds) != len(that1.TaskIds) {
		return fmt1.Errorf("TaskIds this(%v) Not Equal that(%v)", len(this.TaskIds), len(that1.TaskIds))
	}
	for i := range this.TaskIds {
		if this.TaskIds[i] != that1.TaskIds[i] {
			return fmt1.Errorf("TaskIds this[%v](%v) Not Equal that[%v](%v)", i, this.TaskIds[i], i, that1.TaskIds[i])
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *TaskIds) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*TaskIds)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if len(this.TaskIds) != len(that1.TaskIds) {
		return false
	}
	for i := range this.TaskIds {
		if this.TaskIds[i] != that1.TaskIds[i] {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *SpoutMsg) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SpoutMsg)
	if !ok {
		return fmt1.Errorf("that is not of type *SpoutMsg")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *SpoutMsg but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *SpoutMsgbut is not nil && this == nil")
	}
	if this.Command != that1.Command {
		return fmt1.Errorf("Command this(%v) Not Equal that(%v)", this.Command, that1.Command)
	}
	if this.Id != that1.Id {
		return fmt1.Errorf("Id this(%v) Not Equal that(%v)", this.Id, that1.Id)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *SpoutMsg) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SpoutMsg)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Command != that1.Command {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *EmissionMetadata) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*EmissionMetadata)
	if !ok {
		return fmt1.Errorf("that is not of type *EmissionMetadata")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *EmissionMetadata but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *EmissionMetadatabut is not nil && this == nil")
	}
	if this.Command != that1.Command {
		return fmt1.Errorf("Command this(%v) Not Equal that(%v)", this.Command, that1.Command)
	}
	if this.Id != nil && that1.Id != nil {
		if *this.Id != *that1.Id {
			return fmt1.Errorf("Id this(%v) Not Equal that(%v)", *this.Id, *that1.Id)
		}
	} else if this.Id != nil {
		return fmt1.Errorf("this.Id == nil && that.Id != nil")
	} else if that1.Id != nil {
		return fmt1.Errorf("Id this(%v) Not Equal that(%v)", this.Id, that1.Id)
	}
	if len(this.Anchors) != len(that1.Anchors) {
		return fmt1.Errorf("Anchors this(%v) Not Equal that(%v)", len(this.Anchors), len(that1.Anchors))
	}
	for i := range this.Anchors {
		if this.Anchors[i] != that1.Anchors[i] {
			return fmt1.Errorf("Anchors this[%v](%v) Not Equal that[%v](%v)", i, this.Anchors[i], i, that1.Anchors[i])
		}
	}
	if this.Stream != nil && that1.Stream != nil {
		if *this.Stream != *that1.Stream {
			return fmt1.Errorf("Stream this(%v) Not Equal that(%v)", *this.Stream, *that1.Stream)
		}
	} else if this.Stream != nil {
		return fmt1.Errorf("this.Stream == nil && that.Stream != nil")
	} else if that1.Stream != nil {
		return fmt1.Errorf("Stream this(%v) Not Equal that(%v)", this.Stream, that1.Stream)
	}
	if this.Task != nil && that1.Task != nil {
		if *this.Task != *that1.Task {
			return fmt1.Errorf("Task this(%v) Not Equal that(%v)", *this.Task, *that1.Task)
		}
	} else if this.Task != nil {
		return fmt1.Errorf("this.Task == nil && that.Task != nil")
	} else if that1.Task != nil {
		return fmt1.Errorf("Task this(%v) Not Equal that(%v)", this.Task, that1.Task)
	}
	if this.Msg != nil && that1.Msg != nil {
		if *this.Msg != *that1.Msg {
			return fmt1.Errorf("Msg this(%v) Not Equal that(%v)", *this.Msg, *that1.Msg)
		}
	} else if this.Msg != nil {
		return fmt1.Errorf("this.Msg == nil && that.Msg != nil")
	} else if that1.Msg != nil {
		return fmt1.Errorf("Msg this(%v) Not Equal that(%v)", this.Msg, that1.Msg)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *EmissionMetadata) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*EmissionMetadata)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Command != that1.Command {
		return false
	}
	if this.Id != nil && that1.Id != nil {
		if *this.Id != *that1.Id {
			return false
		}
	} else if this.Id != nil {
		return false
	} else if that1.Id != nil {
		return false
	}
	if len(this.Anchors) != len(that1.Anchors) {
		return false
	}
	for i := range this.Anchors {
		if this.Anchors[i] != that1.Anchors[i] {
			return false
		}
	}
	if this.Stream != nil && that1.Stream != nil {
		if *this.Stream != *that1.Stream {
			return false
		}
	} else if this.Stream != nil {
		return false
	} else if that1.Stream != nil {
		return false
	}
	if this.Task != nil && that1.Task != nil {
		if *this.Task != *that1.Task {
			return false
		}
	} else if this.Task != nil {
		return false
	} else if that1.Task != nil {
		return false
	}
	if this.Msg != nil && that1.Msg != nil {
		if *this.Msg != *that1.Msg {
			return false
		}
	} else if this.Msg != nil {
		return false
	} else if that1.Msg != nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *EmissionProto) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*EmissionProto)
	if !ok {
		return fmt1.Errorf("that is not of type *EmissionProto")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *EmissionProto but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *EmissionProtobut is not nil && this == nil")
	}
	if !this.EmissionMetadata.Equal(that1.EmissionMetadata) {
		return fmt1.Errorf("EmissionMetadata this(%v) Not Equal that(%v)", this.EmissionMetadata, that1.EmissionMetadata)
	}
	if len(this.Contents) != len(that1.Contents) {
		return fmt1.Errorf("Contents this(%v) Not Equal that(%v)", len(this.Contents), len(that1.Contents))
	}
	for i := range this.Contents {
		if !bytes.Equal(this.Contents[i], that1.Contents[i]) {
			return fmt1.Errorf("Contents this[%v](%v) Not Equal that[%v](%v)", i, this.Contents[i], i, that1.Contents[i])
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *EmissionProto) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*EmissionProto)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.EmissionMetadata.Equal(that1.EmissionMetadata) {
		return false
	}
	if len(this.Contents) != len(that1.Contents) {
		return false
	}
	for i := range this.Contents {
		if !bytes.Equal(this.Contents[i], that1.Contents[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Test) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Test)
	if !ok {
		return fmt1.Errorf("that is not of type *Test")
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt1.Errorf("that is type *Test but is nil && this != nil")
	} else if this == nil {
		return fmt1.Errorf("that is type *Testbut is not nil && this == nil")
	}
	if this.Name != that1.Name {
		return fmt1.Errorf("Name this(%v) Not Equal that(%v)", this.Name, that1.Name)
	}
	if this.Number != that1.Number {
		return fmt1.Errorf("Number this(%v) Not Equal that(%v)", this.Number, that1.Number)
	}
	if !bytes.Equal(this.Data, that1.Data) {
		return fmt1.Errorf("Data this(%v) Not Equal that(%v)", this.Data, that1.Data)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt1.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *Test) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Test)
	if !ok {
		return false
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Number != that1.Number {
		return false
	}
	if !bytes.Equal(this.Data, that1.Data) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
